language: php

addons:
    postgresql: "9.2"

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

# Note. Only test databases with PHP5.5 because its the fastest
# And we don't need to test for multiple DB versions as the Queries are very common.
matrix:
    include:
        - php: 5.3
          env: DEPENDENCIES='low'
        - php: 5.5
          env: DB=pgsql
        - php: 5.5
          env: DB=sqlite
        - php: 5.6
          env: DEPENDENCIES='dev'
    allow_failures:
        - php: hhvm-nightly
        - env: DEPENDENCIES='dev'
    fast_finish: true

install:
    - export COMPOSER_ROOT_VERSION=dev-master
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$DB" != "" ] ; then travis_retry composer update --prefer-source; fi;
    - if [ "$DEPENDENCIES" != "low" ] && [ "$DB" == "" ] ; then travis_retry composer update; fi;
    - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --prefer-lowest; fi;

script:
    - ./bin/phpunit --configuration phpunit.xml.dist
    - if [ "$DB" != "" ]; then ./bin/phpunit --configuration tests/travis/$DB.travis.xml; fi;
