language: php

sudo: true

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - ES_VERSION="5.x"
        - ES_TEST_HOST=http://localhost:9200

matrix:
    include:
        - php: 7.1
        - php: 7.1
          env: deps='low'
        - php: 7.1
          env: deps='dev'
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
    - export COMPOSER_ROOT_VERSION=dev-master
    - export SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - export SYMFONY_PHPUNIT_VERSION=5.4.8
    - if [[ ! $deps ]]; then composer update --prefer-source --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'dev' ]]; then composer config minimum-stability dev && composer update --prefer-source --no-progress --no-suggest --ansi ; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-source --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - make test
