language: php

sudo: false

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'
        - php: '7.1'
          env: deps='low'
        - php: '7.1'
          env: testcase='doctrine_dbal'
        - php: '7.1'
          env: testcase='doctrine_orm'
        - php: '7.1'
          env: testcase='search_processor'
        - php: '7.1'
          env: testcase='api_platform'
env:
    global:
        - TMPDIR=/tmp

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - |
        if [[ $testcase = 'doctrine_dbal' ]]; then
            composer require --no-update "doctrine/doctrine-bundle:^1.1"
            composer require --no-update "rollerworks/search-doctrine-dbal:^2.0@dev"
        fi;

        if [[ $testcase = 'doctrine_orm' ]]; then
            composer require --no-update "doctrine/doctrine-bundle:^1.1"
            composer require --no-update "rollerworks/search-doctrine-orm:^2.0@dev"
        fi;

        if [[ $testcase = 'search_processor' ]]; then
            composer require --no-update "rollerworks/search-processor:^1.0@dev"
            composer require --no-update "symfony/psr-http-message-bridge:^1.0"
        fi;

        if [[ $testcase = 'api_platform' ]]; then
            composer require --no-update "symfony/twig-bundle:^3.2.4"
            composer require --no-update "doctrine/doctrine-bundle:^1.1"
            composer require --no-update "rollerworks/search-doctrine-orm:^2.0@dev"
            composer require --no-update "rollerworks/search-api-platform:^1.0@dev"
        fi;

install:
    - export SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - export SYMFONY_PHPUNIT_VERSION=6.2
    - export SYMFONY_DEPRECATIONS_HELPER=weak_vendors
    - if [[ ! $deps ]]; then composer update --prefer-source --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'dev' ]]; then composer config minimum-stability dev && composer update --prefer-source --no-progress --no-suggest --ansi ; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-source --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - vendor/bin/simple-phpunit --verbose
