language: php

addons:
    postgresql: "9.2"

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1

# Note. Only test databases with PHP (latest) because its the fastest
# And we don't need to test for multiple DB versions as the Queries are very common.
matrix:
    include:
        - php: 7.1
          env: deps='low'
        - php: 7.1
          env: DB=pgsql
        - php: 7.1
          env: DB=sqlite
        - php: 7.1
          env: DB=mysql
        - php: 7.1
          env: deps='dev'
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
    - export COMPOSER_ROOT_VERSION=dev-master
    - export SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - export SYMFONY_PHPUNIT_VERSION=5.4.8
    - if [[ ! $deps ]]; then composer update --prefer-source --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'dev' ]]; then composer config minimum-stability dev && composer update --prefer-source --no-progress --no-suggest --ansi ; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-source --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

before_script:
    - if [ "$DB" == "mysql" ]; then mysql -e 'create database search_tests;'; fi;

script:
    - vendor/bin/simple-phpunit --verbose
    - if [ "$DB" != "" ] && [ "$DB" != "sqlite" ]; then vendor/bin/simple-phpunit --configuration tests/travis/$DB.travis.xml --exclude-group non-functional; fi;
    - if [ "$DB" = "sqlite" ]; then vendor/bin/simple-phpunit --configuration tests/travis/sqlite.travis.xml; fi;
