language: php

sudo: false

branches:
    only:
        - master
        - 1.x

matrix:
    include:
        - php: 7.0
        - php: 7.1
#        - php: 7.0
#          env: DEPENDENCIES='low'
        - php: 7.0
          env: DEPENDENCIES='dev'
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer selfupdate
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - export SYMFONY_DEPRECATIONS_HELPER=weak
    - export COMPOSER_ROOT_VERSION=dev-master
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$DEPENDENCIES" != "low" ]; then travis_retry composer update; fi;
    - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --prefer-lowest; fi;

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist --verbose
    - vendor/bin/phpspec run
