language: php

sudo: true

services:
    - docker

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'
          #env: coverage=1
#        - php: '7.1'
#          env: deps='low' lint=1

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [[ $coverage = 1 ]]; then mkdir -p build/logs build/cov; fi
    - if [[ $coverage = 1 ]]; then wget https://phar.phpunit.de/phpcov.phar; fi
    - if [[ $coverage = 1 ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi

install:
#    - if [[ $coverage = 1 ]]; then composer require --dev --no-update 'phpunit/php-code-coverage:^5.2'; fi
    - |
        if [[ ! $deps ]]; then
            docker-compose run --rm php make install
        elif [[ $deps = 'dev' ]]; then
            docker-compose run --rm php make install-dev
        elif [[ $deps = 'low' ]]; then
            docker-compose run --rm php make install-lowest
        fi

script:
    - make test-isolated
#    - if [[ $coverage = 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-php build/cov/coverage-phpunit.cov; else vendor/bin/phpunit; fi
#    - if [[ $coverage = 1 ]]; then phpdbg -qrr phpcov.phar merge --clover build/logs/clover.xml build/cov; fi
#    - if [[ $lint = 1 ]]; then php php-cs-fixer.phar fix --dry-run --diff --no-ansi; fi
#    - if [[ $lint = 1 ]]; then phpstan analyse -c phpstan.neon -l5 --ansi src tests; fi

after_success:
    - if [[ $coverage = 1 ]]; then travis_retry php coveralls.phar; fi
